#!/usr/bin/env python3
# Copyright 2026 Robert Leclercq
# SPDX-License-Identifier: Apache-2.0
"""
Owned board IR → src/board/pins_generated.h

Never invents pins. Reads pin strings from IR YAML only.
stub/draft → HAL_PIN_INVALID.
bf-derived / verified / golden / ready → pack pins from YAML (no BF config.h).
Do not vendor GPL config.h into the firmware tree.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PACKABLE = {"bf-derived", "verified", "golden", "ready"}


def _pin_pack(token: str) -> str:
    if not token:
        return "HAL_PIN_INVALID"
    m = re.fullmatch(r"P([A-K])(\d{1,2})", token.strip())
    if not m:
        return "HAL_PIN_INVALID"
    port = ord(m.group(1)) - ord("A")
    num = int(m.group(2))
    if num > 15:
        return "HAL_PIN_INVALID"
    return f"HAL_PIN_PACK({port}u, {num}u)"


def _tim_num(token: str) -> int:
    m = re.fullmatch(r"TIM(\d{1,2})", (token or "").strip())
    return int(m.group(1)) if m else 0


def _field(text: str, key: str, default: str = "") -> str:
    m = re.search(rf"^\s*{re.escape(key)}:\s*(.+)$", text, re.M)
    if not m:
        return default
    v = m.group(1).strip().strip("\"'")
    if v in ("null", "~", ""):
        return default
    return v


def _channel_pins(text: str) -> list[dict]:
    chans: list[dict] = []
    for m in re.finditer(
        r"-\s*\{\s*index:\s*(\d+)\s*,\s*pin:\s*([A-Z0-9]+)\s*,\s*timer:\s*([A-Z0-9]+)\s*,\s*channel:\s*(\d+)",
        text,
    ):
        chans.append(
            {
                "index": int(m.group(1)),
                "pin": m.group(2),
                "timer": m.group(3),
                "channel": int(m.group(4)),
            }
        )
    chans.sort(key=lambda c: c["index"])
    return chans


def parse_ir(raw: str, fallback_id: str) -> dict:
    status = _field(raw, "status", "stub").lower()
    board_id = _field(raw, "board_id", fallback_id)
    mcu = _field(raw, "family", "STM32F722")
    hse = _field(raw, "hse_mhz", "0")
    try:
        hse_i = int(float(hse))
    except ValueError:
        hse_i = 0
    chip = _field(raw, "chip", "none")
    try:
        spi = int(_field(raw, "spi_bus", "0") or "0")
    except ValueError:
        spi = 0
    cs = _field(raw, "cs_pin")
    exti = _field(raw, "exti_pin")
    rx_uart = 0
    tx = rx = ""
    proto = "CRSF"
    sm = re.search(r"serial_rx:\s*\n(?P<body>(?:[ \t].*\n)+)", raw)
    if sm:
        body = sm.group("body")
        um = re.search(r"uart:\s*(\d+)", body)
        if um:
            rx_uart = int(um.group(1))
        pm = re.search(r"pins:\s*\{\s*tx:\s*([A-Z0-9]+)\s*,\s*rx:\s*([A-Z0-9]+)", body)
        if pm:
            tx, rx = pm.group(1), pm.group(2)
        pr = re.search(r"protocol_default:\s*([A-Za-z0-9_]+)", body)
        if pr:
            proto = pr.group(1)
    led0 = _field(raw, "led0_pin")
    return {
        "status": status,
        "board_id": board_id,
        "mcu": mcu,
        "hse": hse_i,
        "chip": chip[:23],
        "spi": spi,
        "cs": cs,
        "exti": exti,
        "rx_uart": rx_uart,
        "tx": tx,
        "rx": rx,
        "proto": proto[:11],
        "led0": led0,
        "vbat": _field(raw, "vbat_pin"),
        "current": _field(raw, "current_pin"),
        "sck": _field(raw, "sck_pin"),
        "miso": _field(raw, "miso_pin"),
        "mosi": _field(raw, "mosi_pin"),
        "align": _field(raw, "gyro_align", "CW0_DEG"),
        "motors": _channel_pins(raw),
        "sd_spi": int(_field(raw,"sd_spi_bus","0")),
        "sd_cs": _field(raw,"sd_cs_pin"),
        "sd_sck": _field(raw,"sd_sck_pin"),
        "sd_miso": _field(raw,"sd_miso_pin"),
        "sd_mosi": _field(raw,"sd_mosi_pin"),
        "sd_detect": _field(raw,"sd_detect_pin"),
    }


def render(src: Path, ir: dict) -> str:
    pack = ir["status"] in PACKABLE
    motors = ir["motors"][:4]
    while len(motors) < 4:
        motors.append({"pin": "", "timer": "", "channel": 0})

    def pin(tok: str) -> str:
        return _pin_pack(tok) if pack else "HAL_PIN_INVALID"

    def tim(tok: str) -> int:
        return _tim_num(tok) if pack else 0

    def ch(n: int) -> int:
        return n if pack and n else 0

    bf = 1 if ir["status"] == "bf-derived" else 0
    verified = 1 if ir["status"] in {"verified", "golden", "ready"} else 0
    dummy = 0 if pack else 1
    spi = ir["spi"] if pack else 0
    uart = ir["rx_uart"] if pack else 0

    license_note = (
        "Pin macros are GPLv3-derived facts from owned IR (not Apache-2.0).\n"
        " * Do not copy Betaflight config.h into this tree. Firmware .c stays Apache-2.0."
        if bf
        else "Pin macros from owned IR. Firmware .c is Apache-2.0."
    )

    lines = [
        "/*",
        " * Copyright 2026 Robert Leclercq",
        " * SPDX-License-Identifier: Apache-2.0",
        " *",
        " * GENERATED by scripts/ir_codegen.py — do not hand-edit.",
        f" * Source IR: {src.as_posix()}",
        f" * IR status: {ir['status']}",
        f" * {license_note}",
        " */",
        "#ifndef BOBFLIGHT_PINS_GENERATED_H",
        "#define BOBFLIGHT_PINS_GENERATED_H",
        "",
        '#include "hal/hal.h"',
        "",
        f'#define BOARD_GENERATED_ID           "{ir["board_id"]}"',
        f'#define BOARD_GENERATED_MCU_FAMILY   "{ir["mcu"]}"',
        f"#define BOARD_GENERATED_HSE_MHZ      {ir['hse']}u",
        f'#define BOARD_GENERATED_GYRO_CHIP    "{ir["chip"] if pack else "none"}"',
        f"#define BOARD_GENERATED_IS_DUMMY     {dummy}",
        f"#define BOARD_GENERATED_IR_VERIFIED  {verified}",
        f"#define BOARD_GENERATED_IR_BF_DERIVED {bf}",
        "",
        f"#define BOARD_GENERATED_SD_SPI {ir['sd_spi'] if pack else 0}u",
        f"#define BOARD_GENERATED_SD_CS {pin(ir['sd_cs'])}",
        f"#define BOARD_GENERATED_SD_SCK {pin(ir['sd_sck'])}",
        f"#define BOARD_GENERATED_SD_MISO {pin(ir['sd_miso'])}",
        f"#define BOARD_GENERATED_SD_MOSI {pin(ir['sd_mosi'])}",
        f"#define BOARD_GENERATED_SD_DETECT {pin(ir['sd_detect'])}",
        f"#define BOARD_GENERATED_GYRO_CS      {pin(ir['cs'])}",
        f"#define BOARD_GENERATED_GYRO_EXTI    {pin(ir['exti'])}",
        f"#define BOARD_GENERATED_GYRO_SPI     {spi}u",
        f"#define BOARD_GENERATED_GYRO_SCK {pin(ir['sck'])}",
        f"#define BOARD_GENERATED_GYRO_MISO {pin(ir['miso'])}",
        f"#define BOARD_GENERATED_GYRO_MOSI {pin(ir['mosi'])}",
        f'#define BOARD_GENERATED_GYRO_ALIGN "{ir["align"]}"', 
        f"#define BOARD_GENERATED_MOTOR1_PIN   {pin(motors[0]['pin'])}",
        f"#define BOARD_GENERATED_MOTOR1_TIM   {tim(motors[0]['timer'])}u",
        f"#define BOARD_GENERATED_MOTOR1_CH    {ch(motors[0]['channel'])}u",
        f"#define BOARD_GENERATED_MOTOR2_PIN   {pin(motors[1]['pin'])}",
        f"#define BOARD_GENERATED_MOTOR2_TIM   {tim(motors[1]['timer'])}u",
        f"#define BOARD_GENERATED_MOTOR2_CH    {ch(motors[1]['channel'])}u",
        f"#define BOARD_GENERATED_MOTOR3_PIN   {pin(motors[2]['pin'])}",
        f"#define BOARD_GENERATED_MOTOR3_TIM   {tim(motors[2]['timer'])}u",
        f"#define BOARD_GENERATED_MOTOR3_CH    {ch(motors[2]['channel'])}u",
        f"#define BOARD_GENERATED_MOTOR4_PIN   {pin(motors[3]['pin'])}",
        f"#define BOARD_GENERATED_MOTOR4_TIM   {tim(motors[3]['timer'])}u",
        f"#define BOARD_GENERATED_MOTOR4_CH    {ch(motors[3]['channel'])}u",
        f"#define BOARD_GENERATED_RX_UART      {uart}u",
        f"#define BOARD_GENERATED_RX_PIN       {pin(ir['rx'])}",
        f"#define BOARD_GENERATED_TX_PIN       {pin(ir['tx'])}",
        f'#define BOARD_GENERATED_RX_PROTO     "{ir["proto"] if pack else "CRSF"}"',
        f"#define BOARD_GENERATED_LED0_PIN    {pin(ir['led0'])}",
        f"#define BOARD_GENERATED_VBAT_PIN    {pin(ir['vbat'])}",
        f"#define BOARD_GENERATED_CURRENT_PIN {pin(ir['current'])}",
        "",
        "#endif /* BOBFLIGHT_PINS_GENERATED_H */",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="BobFlight IR → pins_generated.h")
    ap.add_argument("ir_yaml", type=Path, help="Path to owned board IR YAML")
    ap.add_argument("-o", "--output", type=Path, required=True)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if not args.ir_yaml.is_file():
        print(f"error: IR not found: {args.ir_yaml}", file=sys.stderr)
        return 1

    raw = args.ir_yaml.read_text(encoding="utf-8")
    if "betaflight/config" in raw.lower() and args.ir_yaml.suffix == ".h":
        print("error: refuse GPL config.h — pass owned IR YAML only", file=sys.stderr)
        return 3

    ir = parse_ir(raw, args.ir_yaml.stem)
    text = render(args.ir_yaml, ir)

    if args.dry_run:
        sys.stdout.write(text)
        print(f"# dry-run ok status={ir['status']} board_id={ir['board_id']}", file=sys.stderr)
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"wrote {args.output} status={ir['status']} board_id={ir['board_id']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
