const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const {spawnSync} = require('node:child_process');
const source = fs.readFileSync(path.join(__dirname,'../src/protocol/power.ts'),'utf8');
const mod = {exports:{}};
new Function('exports','require','module', ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(mod.exports,require,mod);
const {parsePower} = mod.exports;
assert.throws(()=>parsePower('unknown — try help'));
assert.throws(()=>parsePower('power_api: 1\n'));
if (!process.argv[2]) throw new Error('Pass the built bobflight_host executable path');
const result=spawnSync(process.argv[2],[],{input:'power_config 11 10 0 6 3.5 3.3 1300\npower\n',encoding:'utf8'});
assert.equal(result.status,0,result.stderr);
const response=result.stdout.slice(result.stdout.indexOf('power_api: 1'),result.stdout.indexOf('power_end: 1')+'power_end: 1'.length);
const parsed=parsePower(response);
assert.equal(parsed.cells,6); assert.equal(parsed.capacity_mah,1300);
assert.equal(parsed.current_mv_per_amp,10); assert.equal(parsed.valid,0);
assert.throws(()=>parsePower(response.replace('valid: 0','valid: NaN')));
assert.throws(()=>parsePower(response.replace('power_end: 1','')));
const rejected=spawnSync(process.argv[2],[],{input:'power_config 11 10 0 6 3.3 3.5 1300\npower\n',encoding:'utf8'});
assert.match(rejected.stdout,/power_config refused/);
assert.match(rejected.stdout,/cells: 0/);
console.log('Power protocol: firmware readback, unknown firmware, truncation, invalid data and atomic rejection passed');
