import {getFilters,getPid,getRates,FILTERS_DEFAULTS,PID_DEFAULTS,RATES_DEFAULTS,resetFilters,resetPid,resetRates,setFilters,setPid,setRates} from "./mockTuningStore";
export const RATE_KEYS=["rate_max_roll","rate_max_pitch","rate_max_yaw","rate_expo"] as const;
export const PID_KEYS=["pid_roll_p","pid_roll_i","pid_roll_d","pid_pitch_p","pid_pitch_i","pid_pitch_d","pid_yaw_p","pid_yaw_i","pid_yaw_d","min_throttle","airmode"] as const;
export const FILTER_KEYS=["gyro_lpf_hz","dterm_lpf_hz"] as const;
export type RateKey=(typeof RATE_KEYS)[number];export type PidKey=(typeof PID_KEYS)[number];export type FilterKey=(typeof FILTER_KEYS)[number];export type SettingsKey=RateKey|PidKey|FilterKey;
const ALL_KEYS:readonly SettingsKey[]=[...RATE_KEYS,...PID_KEYS,...FILTER_KEYS];function isSettingsKey(k:string):k is SettingsKey{return (ALL_KEYS as readonly string[]).includes(k);}
function formatNum(n:number):string{if(Number.isInteger(n))return String(n);const s=n.toFixed(8).replace(/\.?0+$/,"");return s.length?s:"0";}
export function validateFilterHz(value:number):boolean{if(!Number.isFinite(value))return false;if(value===0)return true;return value>=10&&value<=1000;}
function readValue(key:SettingsKey):number{if((RATE_KEYS as readonly string[]).includes(key))return getRates()[key as RateKey];if((FILTER_KEYS as readonly string[]).includes(key))return getFilters()[key as FilterKey];return getPid()[key as PidKey];}
function writeValue(key:SettingsKey,value:number):boolean{if(!Number.isFinite(value))return false;if((RATE_KEYS as readonly string[]).includes(key)){setRates({...getRates(),[key]:value});return true;}if((FILTER_KEYS as readonly string[]).includes(key)){if(!validateFilterHz(value))return false;setFilters({...getFilters(),[key]:value});return true;}setPid({...getPid(),[key]:value});return true;}
export function parseKeyValue(line:string):{key:string;value:string}|null{const trimmed=line.trim();const idx=trimmed.indexOf("=");if(idx<=0)return null;const key=trimmed.slice(0,idx),value=trimmed.slice(idx+1);if(!key||value==='')return null;if(/\s/.test(key)||line.includes(" =")||line.includes("= "))return null;return {key,value};}
export function parseGetReply(reply:string):{key:string;value:number}|null{const line=reply.trim().split(/\r?\n/)[0]??"";if(line==="unknown key"||line==="set failed"||line==="save failed")return null;const kv=parseKeyValue(line);if(!kv)return null;const n=Number(kv.value);return Number.isFinite(n)?{key:kv.key,value:n}:null;}
export function parseSetReply(reply:string):{ok:true;key:string;value:number}|{ok:false;error:string}{const line=reply.trim().split(/\r?\n/)[0]??"";if(line==="unknown key"||line==="set failed"||line==="save failed")return {ok:false,error:line};if(!line.startsWith("ok "))return {ok:false,error:line||"set failed"};const kv=parseKeyValue(line.slice(3));if(!kv)return {ok:false,error:"set failed"};const n=Number(kv.value);return Number.isFinite(n)?{ok:true,key:kv.key,value:n}:{ok:false,error:"set failed"};}
export const mockSettingsApi={get(key:string):string{if(!isSettingsKey(key))return "unknown key";return `${key}=${formatNum(readValue(key))}`;},set(key:string,value:number|string):string{if(!isSettingsKey(key))return "unknown key";const n=typeof value==='number'?value:Number(value);if(!Number.isFinite(n))return "set failed";if(!writeValue(key,n))return "set failed";return `ok ${key}=${formatNum(readValue(key))}`;},save():string{return "saved";},defaults(scope:"rates"|"pid"|"filters"|"all"="all"):string{if(scope==="rates"||scope==="all")resetRates();if(scope==="pid"||scope==="all")resetPid();if(scope==="filters"||scope==="all")resetFilters();return "defaults restored";},getAll(keys:readonly SettingsKey[]):Record<string,number>{const out:Record<string,number>={};for(const key of keys){const parsed=parseGetReply(this.get(key));if(parsed)out[parsed.key]=parsed.value;}return out;},defaultsSnapshot(){return {rates:{...RATES_DEFAULTS},pid:{...PID_DEFAULTS},filters:{...FILTERS_DEFAULTS}};}};
